apiVersion: apps/v1
kind: Deployment
metadata:
  name: furniture-deployment
  labels:
    app: furniture
spec:
  replicas: 1
  selector:
    matchLabels:
      app: furniture
  template:
    metadata:
      labels:
        app: furniture
    spec:
      containers:
      - name: furniture
        image: 852492841325.dkr.ecr.us-east-1.amazonaws.com/shopping-site-furniture:e4887ad2a9bd6d1725bae83adc665da3e0155603
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: furniture-service
  labels:
    app: furniture
spec:
  type: ClusterIP
  selector:
    app: furniture
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
