
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: 852492841325.dkr.ecr.us-east-1.amazonaws.com/shopping-site-backend:d3b636cda2b122568221cca53718873247139203
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: backend-config

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP